[tool.poetry]
name = "hw-4"
version = "0.1.0"
description = ""
authors = ["Delah0ya <viktor.deleichuk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "3.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
